"""Initial migration

Revision ID: ed5e5404e31f
Revises: 8bb9ca1fdb3f
Create Date: 2024-09-16 09:21:49.569630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5e5404e31f'
down_revision: Union[str, None] = '8bb9ca1fdb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###