"""Add avatar column to User model

Revision ID: fa8c8234cedf
Revises: 11b13ab151d5
Create Date: 2024-09-26 20:43:48.282772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8c8234cedf'
down_revision: Union[str, None] = '11b13ab151d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('confirmed_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_email')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###